<a href="https://colab.research.google.com/github/NamSee04/CS114.P11/blob/main/CS114_P11_Tool_DatasetStat_Car.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# THỐNG KÊ DỮ LIỆU

1. Yêu cầu chung: Thống kê được số lượng ảnh trong từng phân loại mà mỗi SV đóng góp

2. Yêu cầu cụ thể:
- Input:
    + Thư mục cha chứa các thư mục con - mỗi thư mục con tương ứng với tên của từng hiệu xe (Honda, Suzuki, VinFast, Others). Ví dụ: https://drive.google.com/drive/u/1/folders/1Uj0V9URNHpzSHeXHSB89AoGCjGki8Yra
    + Các ảnh được đặt tên theo quy ước: các tập tin ảnh theo quy ước https://colab.research.google.com/drive/1bUmXMM_ggnEXKo2qylfe6h0JnQuos-8_
- Output:
    + File CarDataset-1.csv - Thống kê số lượng ảnh theo từng SV
      + Mỗi dòng sẽ có các thông tin cách nhau bằng dấu phẩy, theo quy ước: MSSV, All, Số lượng.
        
        Ví dụ: 20221234, All, 1.2
      + Số lượng có thể là số thực vì một ảnh có thể có đóng góp từ nhiều sinh viên
    + File CarDataset-2.csv - Thống kê số lượng ảnh theo từng Hiệu xe mà từng SV đóng góp
      + Mỗi dòng sẽ có các thông tin cách nhau bằng dấu phẩy, theo quy ước: MSSV, Hiệu xe, Số lượng.
        
        Ví dụ: 20221234, Honda, 1.2
      + Số lượng có thể là số thực vì một ảnh có thể có đóng góp từ nhiều sinh viên
      + Chỉ chấp nhận file .jpg, .jpeg và .png
3. Nộp bài: SV share notebook. Các bài nộp sớm sẽ được full điểm. Deadline: 17:00 - ??/??/2024

4. Bài làm đạt yêu cầu sẽ được paste vào notebook với ghi nhận đóng góp từ tác giả.

In [1]:
from google.colab import drive
import os

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import csv

# Hỗ trợ các định dạng file hợp lệ
VALID_EXTENSIONS = {'.jpg', '.jpeg', '.png'}

def parse_file_name(file_name):
    """Phân tích tên file để lấy MSSV, hãng xe, và tỷ lệ đóng góp."""
    try:
        base_name, _ = os.path.splitext(file_name)
        mssv, brand, contribution = base_name.split('.')
        return mssv, brand
    except (ValueError, IndexError):
        return None, None

def process_directory(root_dir):
    """Duyệt thư mục và thống kê số lượng ảnh."""
    student_contributions = {}
    car_brand_contributions = {}

    for car_brand in os.listdir(root_dir):
        brand_dir = os.path.join(root_dir, car_brand)
        if not os.path.isdir(brand_dir):
            continue
        print(brand_dir)
        for file_name in os.listdir(brand_dir):
            file_path = os.path.join(brand_dir, file_name)
            if os.path.splitext(file_name)[-1].lower() not in VALID_EXTENSIONS:
                continue

            mssv, brand = parse_file_name(file_name)
            if mssv and brand is not None:
                # Tổng hợp số lượng ảnh (All)
                if mssv not in student_contributions:
                    student_contributions[mssv] = 0
                student_contributions[mssv] += 1

                # Tổng hợp số lượng ảnh theo hãng xe
                if mssv not in car_brand_contributions:
                    car_brand_contributions[mssv] = {}
                if brand not in car_brand_contributions[mssv]:
                    car_brand_contributions[mssv][brand] = 0
                car_brand_contributions[mssv][brand] += 1

    return student_contributions, car_brand_contributions

def write_csv(file_path, data, headers):
    """Ghi dữ liệu ra file CSV."""
    with open(file_path, mode='w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(headers)
        for row in data:
            writer.writerow(row)

def main():
    root_dir = "/content/drive/MyDrive/Public"  # Đường dẫn thư mục gốc
    output_1 = "CarDataset-1.csv"
    output_2 = "CarDataset-2.csv"

    # Thống kê dữ liệu
    student_contributions, car_brand_contributions = process_directory(root_dir)

    # Xuất file CarDataset-1.csv
    data_1 = [(mssv, "All", round(total, 2)) for mssv, total in student_contributions.items()]
    write_csv(output_1, data_1, headers=["MSSV", "All", "Số lượng"])

    # Xuất file CarDataset-2.csv
    data_2 = []
    for mssv, brands in car_brand_contributions.items():
        for brand, total in brands.items():
            data_2.append((mssv, brand, round(total, 2)))
    write_csv(output_2, data_2, headers=["MSSV", "Hiệu xe", "Số lượng"])

    print(f"Đã tạo {output_1} và {output_2} thành công!")

if __name__ == "__main__":
    main()

/content/drive/MyDrive/Public/Mazda
/content/drive/MyDrive/Public/Mitsubishi
/content/drive/MyDrive/Public/Suzuki
/content/drive/MyDrive/Public/Toyota
/content/drive/MyDrive/Public/Hyundai
/content/drive/MyDrive/Public/KIA
/content/drive/MyDrive/Public/VinFast
/content/drive/MyDrive/Public/Others
/content/drive/MyDrive/Public/Honda
Đã tạo CarDataset-1.csv và CarDataset-2.csv thành công!

In [3]:
import pandas as pd
df1 = pd.read_csv('CarDataset-1.csv')
df2 = pd.read_csv('CarDataset-2.csv')

In [8]:
df1.head()

                         MSSV  All  Số lượng
0  22521027-22520195-22521060  All     11969
1           22520477-22520490  All       581
2           22520914-22520915  All       662
3           22521560-22521614  All       448
4           22520779-22521587  All      2730

In [9]:
df2.head()

                         MSSV     Hiệu xe  Số lượng
0  22521027-22520195-22521060       Mazda      1023
1  22521027-22520195-22521060  Mitsubishi      1000
2  22521027-22520195-22521060      Suzuki      2307
3  22521027-22520195-22521060      Toyota      2218
4  22521027-22520195-22521060     Hyundai      1111